name: Build and publish image

on: [ push ]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sign In
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Prepare original images
        run: |
          docker pull php:8.0-fpm-alpine \
            & docker pull php:8.0-apache

      - name: Build
        run: |
          docker build -t php-fpm .
          docker build -t php-apache -f php-apache.Dockerfile .

      - name: Publish images
        run: |
          docker tag php-fpm parsilver/php-8.0:latest
          docker tag php-apache parsilver/php-8.0:apache
          docker push parsilver/php-8.0:latest
          docker push parsilver/php-8.0:apache
